services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "StrongPassword123!"
      POSTGRES_DB: student_portal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d student_portal"]
      interval: 10s
      timeout: 5s
      retries: 5
